In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Production mix disaggregation

In [15]:
production_mix = pd.read_excel('./DH production mix/four_category.xlsx', sheet_name='agg')
production_mix.index = pd.to_datetime(production_mix['month'].astype(str).str.strip(), format='%Y-%m')
production_mix.drop(columns=['month'], inplace=True)

In [16]:
priority_sources = ['Waste heat', 'Electricity', 'Biomass', 'Fossil fuel']
years = range(2021, 2026)
daily_df = pd.DataFrame()

frames = []

for yr in years:
    daily = pd.read_csv(
        f'./DH production mix/daily_{yr}.csv',
        parse_dates=['date']
    )
    daily = daily.set_index('date')
    daily_df = pd.concat([daily_df, daily[priority_sources]])

    # Sum source columns + total per calendar month
    agg = daily[priority_sources + ['daily_total_mwh']].resample('ME').sum()
    frames.append(agg)

# production_disagg = pd.concat(frames)   # stack all years
# production_disagg.index.name = 'month'
# production_disagg.index = production_disagg.index.strftime('%Y-%m')
# production_disagg = production_disagg.rename(columns={'daily_total_mwh': 'monthly_total_mwh'})

display(daily_df.head())

             Waste heat  Electricity     Biomass  Fossil fuel
date
2021-01-01  1831.322581   162.580645  788.082089   742.342874
2021-01-02  1831.322581   162.580645  788.082089   416.767460
2021-01-03  1831.322581   162.580645  788.082089  1051.228698
2021-01-04  1831.322581   162.580645  788.082089  1095.905450
2021-01-05  1831.322581   162.580645  788.082089  1096.418976

In [17]:
production_mix = production_mix.apply(pd.to_numeric)
production_mix['monthly_total_mwh'] = production_mix.sum(axis=1)
production_mix.index = production_mix.index.strftime('%Y-%m')
display(production_mix.head())

         Waste heat  Electricity  Biomass  Fossil fuel  monthly_total_mwh
month
2021-01       56771         5040  24228.0        26654           112693.0
2021-02       49186         4760  19487.0        20229            93662.0
2021-03       55311          401  13333.0         2577            71622.0
2021-04       49095          610  10910.0         1707            62322.0
2021-05       34248          418    756.0         3360            38782.0

In [19]:
# priority_sources = ['Waste heat', 'Electricity', 'Biomass', 'Fossil fuel']
# source_colors    = ['#2196F3', '#FF9800', '#4CAF50', '#F44336']

# fig, ax = plt.subplots(figsize=(12, 6))

# daily_2023 = daily_df[daily_df.index.year==2023]

# # Plot as stacked area
# daily_2023[priority_sources].plot.area(
#     ax=ax, 
#     stacked=True, 
#     color=source_colors, 
#     alpha=0.85
# )

# ax.set_title('Energy Production Mix Trend', fontsize=14, fontweight='bold', pad=15)
# ax.set_xlabel('Date', fontsize=12)
# ax.set_ylabel('Energy Production (MWh)', fontsize=12)
# ax.grid(axis='y', linestyle='--', alpha=0.3)
# ax.legend(title='Energy Source', bbox_to_anchor=(1.05, 1), loc='upper left')

# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()