In [1]:
import pandas as pd
import numpy as np

In [21]:
production_mix = pd.read_excel('./DH production mix/four_category.xlsx', sheet_name='agg')
production_mix.index = pd.to_datetime(production_mix['month'].astype(str).str.strip(), format='%Y-%m')
production_mix.drop(columns=['month'], inplace=True)

In [11]:
priority_sources = ['Waste heat', 'Electricity', 'Biomass', 'Fossil fuel']
years = range(2021, 2026)

frames = []

for yr in years:
    daily = pd.read_csv(
        f'./DH production mix/daily_{yr}.csv',
        parse_dates=['date']
    )
    daily = daily.set_index('date')

    # Sum source columns + total per calendar month
    agg = daily[priority_sources + ['daily_total_mwh']].resample('ME').sum()
    frames.append(agg)

production_disagg = pd.concat(frames)   # stack all years
production_disagg.index.name = 'month'
production_disagg.index = production_disagg.index.strftime('%Y-%m')
production_disagg = production_disagg.rename(columns={'daily_total_mwh': 'monthly_total_mwh'})

display(production_disagg.head())

         Waste heat  Electricity  Biomass  Fossil fuel  monthly_total_mwh
month
2021-01     56771.0       5040.0  24228.0      26654.0           112693.0
2021-02     49186.0       4760.0  19487.0      20229.0            93662.0
2021-03     55311.0        401.0  13333.0       2577.0            71622.0
2021-04     49095.0        610.0  10910.0       1707.0            62322.0
2021-05     34248.0        418.0    756.0       3360.0            38782.0

In [25]:
production_mix = production_mix.apply(pd.to_numeric, errors = 'coerce')
production_mix['monthly_total_mwh'] = production_mix.sum()
display(production_mix.head())

            Waste heat  Electricity  Biomass  Fossil fuel  monthly_total_mwh
month
2021-01-01       56771         5040  24228.0        26654                NaN
2021-02-01       49186         4760  19487.0        20229                NaN
2021-03-01       55311          401  13333.0         2577                NaN
2021-04-01       49095          610  10910.0         1707                NaN
2021-05-01       34248          418    756.0         3360                NaN